### ISSUE TITLE
[1.18.1] Sage + seeds cannot be composted

### ISSUE THREAD

**Issue by Febilian** [JoeFoxe/Hexerei-1.18#11]
This may also happen with other herbs, but haven't found any of them yet though so I can't say definitively.

With sage I feel it's particularly important because you get an awful lot of the seeds from breaking grass, and quickly end up with more than you'd ever want to actually plant.

**Comment by JoeFoxe** [comment]
Actually this is fixed in my most recent dev version :D so whenever im feeling ready to upload the next update it will be in there :)
