### ISSUE TITLE
Possible bug report and suggestion

### ISSUE THREAD

**Issue by KamiSami** [JoeFoxe/Hexerei-1.18#12]
Hi, i was testing out your mod for a bit and found something mildly upsetting, the contents of broom (Including large bag, misc and brush, so whole inventory gone too whatever is stored) seemed to vanish, i am not sure what was the cause of it, i was jumping and placing it on top of lilypads as i was thinking of going to fly, but i noticed the brush was gone, and when i checked contents of broom, all was gone, again im not sure what caused this happen exactly, but for sure it happened... I don't know if it can be because going on and off creative mode which i had done few times during testings as i remember some mods inventories not liking that sometimes... But anyway, this bug seems to be present, clueless though how it happens exactly, haven't been able to reproduce it again just yet... This happened in hexerei-0.1.13. If i find exact method how it happened i will let you know, unless you may have idea what could cause it to happen. Also simple suggestion, could you link "issues" link in curseforge leading to here in github, if you want bug reports? Most mods have that if they have source too as far as i remember. I got here from source link.

**Comment by JoeFoxe** [comment]
oh my god im so sorry this happened to you :( I will definitely look into it, I have no idea what could possibly have happened to you with the broom. I have been playing for a while on a server and havent come across such issues. I will look into it but it is hard to look for something like that when I havent seen it happen yet. but I feel super bad about that I know how much that can suck

**Comment by KamiSami** [comment]
It's alright, i have not yet found either as of why it happened, been unable to reproduce the bug >_<; Again, i will let you know if i do somehow manage to do it again and see what could be the reason for it to happen

**Comment by JoeFoxe** [comment]
fixed in the latest update :) (soon to come)
