### ISSUE TITLE
Mahogany trees spawn on water

### ISSUE THREAD

**Issue by mosharky** [JoeFoxe/Hexerei-1.18#13]
Mahogany trees don't check for the block they're spawning on, so they just spawn on water blocks as long as it meets the requirements

**Comment by mosharky** [comment]
Here's a screenshot by the way, this is in Biomes O Plenty's rainforest biome (which already generates Mahogany trees):
![image](https://user-images.githubusercontent.com/32606683/152277083-003f4070-f24b-4473-bb36-73b4d0557abb.png)

**Comment by ffuentesm** [comment]
Same here, but I am not using any terrain mod. 
![image](https://user-images.githubusercontent.com/44974827/152467177-6f271664-82b4-4930-83f4-a18df7bb64c4.png)

**Comment by JoeFoxe** [comment]
completely fixed in the new update :) I just didnt say anything in here as I was implementing it still
