### ISSUE TITLE
Dropping a dowsing rod or placing a dowsing rod into an item frame causes game crash

### ISSUE THREAD

**Issue by FreshAlacrity** [JoeFoxe/Hexerei-1.18#15]
Originally reported by @BronzeShadow on the Hexerei Discord, you can see their post here: https://discord.com/channels/908547504587538463/911421279108747296/939496247310577674

To replicate: using the latest version of Hexerei (hexerei-0.1.14.jar) place an item frame anywhere and place the dowsing rod into it (game crashes immediately)

The original crash report from BronzeShadow: [BronzeShadow_original_crash_report.txt](https://github.com/JoeFoxe/Hexerei-1.18/files/8008391/BronzeShadow_original_crash_report.txt)

Crash report from my WIP modpack: [alec_modpack_crash_report.txt](https://github.com/JoeFoxe/Hexerei-1.18/files/8008392/alec_modpack_crash_report.txt)

Crash report for only Hexerei mod using latest Forge in a new world + fresh profile:  
[crash-2022-02-05_11.45.03-client.txt](https://github.com/JoeFoxe/Hexerei-1.18/files/8008398/crash-2022-02-05_11.45.03-client.txt)

**Comment by FreshAlacrity** [comment]
Crash log for just throwing it with Q (edited title also)
[crash-2022-02-08_12.40.12-client.txt](https://github.com/JoeFoxe/Hexerei-1.18/files/8026204/crash-2022-02-08_12.40.12-client.txt)

**Comment by FreshAlacrity** [comment]
Luckily loading back into the world works fine (the first time at least???)

Thanks to @Frog from the Discord server for reporting the drop/throw issue and this bit also! 💚

**Comment by JoeFoxe** [comment]
fixed in the latest update (soon to come)
