### ISSUE TITLE
Z fighting for ice filled lily pads 

### ISSUE THREAD

**Issue by drhaber** [JoeFoxe/Hexerei-1.18#16]
With TFC installed which causes water to freeze with its change in seasons Hexerei lily pads will remain on top of ice blocks and z fight with them 

![image](https://user-images.githubusercontent.com/56454522/152651033-ef94562b-3972-4b7b-a0dc-5c474321acb4.png)

**Comment by JoeFoxe** [comment]
finally fixed in the next upcoming update :)
