### ISSUE TITLE
Broom contents disappearing

### ISSUE THREAD

**Issue by FreshAlacrity** [JoeFoxe/Hexerei-1.18#17]
Reported on the Hexerei Discord; haven't been able to reproduce it sadly; just putting an issue here with what we know so that hopefully anybody else that has this happen can add more details and we can figure out what's up!

Minecraft Version: 1.18.1
Forge Version: 39.0.10
Hexerei Version: 0.1.13

(might involve a possible conflict with Blackpacked v2.0.0 but I didn't see any related issues on their GitHub)

**Comment by FreshAlacrity** [comment]
Further testing seems to absolve Backpacked of any relation, still unclear what the cause might be

**Comment by FreshAlacrity** [comment]
This bug has been reproduced! 🎊

**Steps to replicate the issue:**
Get yourself a mahogany broom, a large satchel, a herb enhanced broom brush, a netherite broom tip, and ~2k diamonds
Attach the satchel and equip the brush and tip, then fill the satchel entirely with diamonds
Break the broom entity while in Survival mode

**Result:** Broom item that is picked up has no brush, tip, satchel, or contents (and when re-placed looks like a stick, as expected)
**Expected Result:** Broom item should keep contents and attachments

**Comment by FreshAlacrity** [comment]
Reproduced in a fresh profile with only Hexerei installed ✨
Forge: 39.0.75
Hexerei: 0.1.14
Minecraft: 1.18.1

Note: the enhanced broom brush isn't necessary - just the netherite tip and entirely full satchel will do the trick (a regular broom brush and full large satchel does not cause the issue)

Not sure if these will be handy but just in case (output log didn't note anything):
[debug.log](https://github.com/JoeFoxe/Hexerei-1.18/files/8042845/debug.log)
[latest.log](https://github.com/JoeFoxe/Hexerei-1.18/files/8042846/latest.log)

**Comment by FreshAlacrity** [comment]
Notes:
- a broom with a satchel that is holding many full coffers has no issue, even with a netherite tip, as long as it is not *completely full* of coffers
- a broom that is completely full of snowballs with a netherite tip disappears, so stack size isn't important
- when holding shift to crouch and open the broom, any throwable item is thrown (will start a separate issue for that)
- the slots don't even need to be completely filled, just occupied: putting a single snowball in every space will cause the issue to occur
- the waterproof tip, rings, and keychain attachments have the same problem, not just the netherite tip
- the broom must have a brush to cause the issue, but it doesn't matter if the brush is enhanced or enchanted

**So, revised steps to reproduce:**
Obtain a broom with any type of brush and any type of tip or decorative attachment and a specifically large satchel, fill every slot in the satchel with at least one item, then break in survival mode to cause the contents to disappear

**Comment by JoeFoxe** [comment]
fixed in the latest update I do believe so :) (coming very soon)
