### ISSUE TITLE
Crash 1.18.1

### ISSUE THREAD

**Issue by Draxterio** [JoeFoxe/Hexerei-1.18#20]
Every time i try to load up in a single player world, mod crashes my game. When I get into the server with the mod included, extreme low FPS. I tested out using multiple mods and removed Hexerei to determine whether or not it was my pc and i was able to run alot of mods with higher file sizes and I had no problems with singleplayer crashing and my multiplayer server having low FPS. When I use Hexerei along with the current mods I am using, singleplayer would crash and I would have low FPS in my multiplayer server.

**Comment by IXaar1** [comment]
Could you attach log or crash report, please?

**Comment by Draxterio** [comment]
There wasnt a specific log that was directly linked to the crash, as I am loading into another world in singleplayer, I got stuck in the loading screen until it crashed and I only got this error message
![Screenshot 2022-02-14 124511](https://user-images.githubusercontent.com/99302672/153935404-9e89f3fb-c3c9-4866-822e-e7626bd4d955.png)
_

**Comment by Draxterio** [comment]
And for multiplayer there was also no other logs referring to a drop of FPS on the server

**Comment by IXaar1** [comment]
You can find game logs here: %AppData%/Roaming/.minecraft/logs
