### ISSUE TITLE
Crash during travel (1.18.1)

### ISSUE THREAD

**Issue by Toma400** [JoeFoxe/Hexerei-1.18#22]
Today I wandered through (btw really beautiful) world and then crash happened.

Latest.log:
[latest.log](https://github.com/JoeFoxe/Hexerei-1.18/files/8068326/latest.log)

NotEnoughCrashes report:
[crash-2022-02-15_11.33.01-server.txt](https://github.com/JoeFoxe/Hexerei-1.18/files/8068327/crash-2022-02-15_11.33.01-server.txt)

**Comment by JoeFoxe** [comment]
fixed in the latest update (soon to come)
