### ISSUE TITLE
Logs Missing Tags

### ISSUE THREAD

**Issue by SapphiCat** [JoeFoxe/Hexerei-1.18#25]
Logs currently missing tags for either:
  * **\#minecraft:logs_that_burn**
  * **\#minecraft:non_flammable_wood**

Log variants other than willow_log and mahogany_log are also missing the **\#minecraft:logs** tag
  
As well as wood type grouping tags, which would be (following common convention)
  * **\#hexerei:willow_logs**, containing:
    * hexerei:willow_log
    * hexerei:willow_wood
    * hexerei:stripped_willow_log
    * hexerei:stripped_willow_wood
  * **\#hexerei:mahogany_logs**, containing: 
    * hexerei:mahogany_log
    * hexerei:mahogany_wood
    * hexerei:stripped_mahogany_log
    * hexerei:stripped_mahogany_wood
    
This has a few small but tangible effects on gameplay - 
  * \#minecraft:logs_that_burn tag: used in the vanilla charcoal recipe
  * \#minecraft:logs is used in the vanilla campfire recipe
  * and more, depending on how other mods reference these tags. 
  
  One last thing, almost forgot: the wood (6-sided bark) recipe creates only one item, where vanilla recipes create three.

**Comment by JoeFoxe** [comment]
oh hey thanks! sorry I have been away for some time, but I have fixed this up in the upcoming update!
