### ISSUE TITLE
[1.18] Sage Missing Tags 

### ISSUE THREAD

**Issue by ffuentesm** [JoeFoxe/Hexerei-1.18#26]
The sage seeds have missing forge tags that are normally found for compatibility. 
![image](https://user-images.githubusercontent.com/44974827/158492869-99db0269-3a22-464f-92ef-3b617a00e5e2.png)
![image](https://user-images.githubusercontent.com/44974827/158492883-4ec63241-bea9-43ca-9a2d-5349a46c972f.png)
Could you add the missing forge tags for better compatibility?

**Comment by JoeFoxe** [comment]
fixed in the next update :)
