### ISSUE TITLE
Crash related to bush plants added by this mod

### ISSUE THREAD

**Issue by cmihran** [JoeFoxe/Hexerei-1.18#27]
I'm running into a server crash/error log I think is related to the bush plants added by this mod. When i bonemeal the bushs (i tried with Mugwort and Yellow Dock Bush) i'll see errors like the following printed out in my server console:

```
[12.04 03:13:23] [Server] Caused byjava.lang.IllegalArgumentException: Cannot set property IntegerProperty{name=age, clazz=class java.lang.Integer, values=[0, 1, 2, 3]} as it does not exist in Block{minecraft:air}
[12.04 03:13:23] [Server] 	at net.minecraft.world.level.block.state.StateHolder.m_61124_(StateHolder.java:117) ~[server-1.18.1-20211210.034407-srg.jar%23279!/:?]
[12.04 03:13:23] [Server] 	at net.joefoxe.hexerei.block.custom.PickableDoubleFlower.m_7455_(PickableDoubleFlower.java:118) ~[hexerei-0.1.14.jar%23144!/:0.1.14]
```

I truncated the stack trace a bit. You can see full stack trace and crash report here: https://pastebin.com/raw/LdC1YjzV

I'm running All the Mods 7 so not sure if it's related to another mod I'm running. Maybe something that happens to interact with harvesting, if that is the case I can redirect the issue to the modpack. But figured I'd start here since its happening with vanilla bonemeal.

It doesn't seem to always crash the server, but if I do it long enough it does crash as seen in the report I linked above.

**Comment by JoeFoxe** [comment]
Will be fixed in the next update :D

**Comment by xAlicatt** [comment]
I'm still running into this crash any time I visit swamps. It seems pretty random and happens fairly often. 

Was this only patched in the 1.18.2 version, or did the 1.18.1 get it too? I'm on 1.18.1.

https://pastebin.com/HFH41iu1

**Comment by JoeFoxe** [comment]
oh dangit.. I thought I fixed this but I see how there still might be an issue, now it should have all the checks in place to change the blockstates values properly if they exist (in the next version of 1.18.2)

**Comment by xAlicatt** [comment]
Was really hoping to see it updated in 1.18.1 as well, but I understand not wanting to support older versions.

**Comment by xAlicatt** [comment]
@JoeFoxe I would even be willing to slide you some cash to update the 1.18.1 version if needed? I have been working on this personal pack for weeks now and all of the mods I'm using are not updated for 1.18.2 yet. This is a game breaking bug and your mod is really important to my pack.

**Comment by JoeFoxe** [comment]
> 

I really am sorry, I wish I could but I did a stupid and didnt save a copy of 1.18.1 before updating. and my github is very very behind. I really am sorry I wish I could help. I mean I could use the cash for sure but its definitely something I would have to spend days on at this point to revert all of the 1.18.2 changes and thats just not something I could really do smoothly and easily

**Comment by xAlicatt** [comment]
I do appreciate your response! I am going to try rolling back to a version that won't crash :) Thanks anyway!

**Comment by JoeFoxe** [comment]
I hope for a speedy update on the other mods parts so you can enjoy the new features :)
