### ISSUE TITLE
[1.18.2] Cannot set property IntegerProperty (Doubleflower)

### ISSUE THREAD

**Issue by Gbergz** [JoeFoxe/Hexerei-1.18#29]
Title ^

Not entirely sure what caused it. But crash report is below.

**Crash Report**: https://gist.github.com/Gbergz/8236899af4d3eb17865e7ea1fea85eae

**Versions**
Forge: 40.1.0
Hexerei: 0.1.18 | https://www.curseforge.com/minecraft/mc-mods/hexerei/files/3775805

**-** Gbergz

**Comment by JoeFoxe** [comment]
Okay this is fully actually fixed this time. I didnt have a check in place if the generation accidentally deletes top part of the flower and not the bottom and then the bottom tries to grow both top side and bottom part of the flower at the same time so they dont break, but being that the top doesnt exist it breaks lol so I made extra checks so it should be good for sure in the next update!

**Comment by Gbergz** [comment]
Sweet, do you have an ETA on when that fix is out? Kind of plagues our server.

**Comment by JoeFoxe** [comment]
Should hopefully be either today or tomorrow, im hoping for today! I am fixing a load of bugs as well as adding a bunch of coloring options for other items.

**Comment by JoeFoxe** [comment]
> Sweet, do you have an ETA on when that fix is out? Kind of plagues our server.

should be up now! sorry about the delay there was some bugs that kept popping up  with the new herb jar being a target for the crows to deposit items as well but fixed that all up and everything is running smoothly!
