### ISSUE TITLE
[1.18.2] Recipe don't show up.

### ISSUE THREAD

**Issue by SkaOArt** [JoeFoxe/Hexerei-1.18#34]
I currently discover this mod. But it seems I have a problem, cause no recipe in JEI show up. It seems also very inconsistend. I can only see how I can craft the couldron, crow flute and the drying rack. ALso all wood recipies. But every other recipy will not show up and i can't let me display the uses. I can't see all the couldron recipy. It's wierd.

**Comment by mobiusdt** [comment]
I had a similar issue with JEI not showing the recipes that require hexerei provided crafters, specifically the most recent JEI release version and the alphas that come out recently. However, JEI beta version 1.18.2-9.7.0.196  (released on 6/7/2022) did work, and correctly shows all of the recipes.

**Comment by JoeFoxe** [comment]
0.2.1 hexerei version with the latest version of JEI should fix. sorry its been so long
