### ISSUE TITLE
Please reconsider CurseForge third-party distribution setting

### ISSUE THREAD

**Issue by copygirl** [JoeFoxe/Hexerei-1.18#35]
Apologies for the lack of a personalized message, but I will be contacting a number of modders today.
Your mod, Hexerei, is one of the few that can't be downloaded by third-party launchers and other tools.
With the following GitHub Gist I would like to try changing your mind, and those of other creators.

https://gist.github.com/copygirl/7d45bad739453d2be61138cebafce04c

Thank you for your work! :green_heart:

**Comment by DDriggs00** [comment]
+1 Many people prefer not to use the curseforge launcher due privacy concerns, and this makes it extremely difficult to use more privacy-friendly launchers.

**Comment by JoeFoxe** [comment]
see [#38](https://github.com/JoeFoxe/Hexerei-1.18/issues/38)
