### ISSUE TITLE
[Suggestion] Allow NBT support wtih items and fluids in the Mixing Cauldron

### ISSUE THREAD

**Issue by Shibva** [JoeFoxe/Hexerei-1.18#37]
Im working on making some custom recipes using your cauldron but ran into the issue that it seems like its not supporting any sort of NBT data that I try to attach to the items and/or fluid; thus making me harder for me to create unique recipes that rely on NBT data 

please consider adding this and if it is already a thing then please provide me with a recipe example of one using it. Thanks in advance ^w^

**Comment by JoeFoxe** [comment]
this is a good idea :) I will actually be working on this eventually  :) hopefully next update but 
I have a ton to do
