### ISSUE TITLE
Crash when rendering book of shadows altar

### ISSUE THREAD

**Issue by Rover656** [JoeFoxe/Hexerei-1.18#45]
A player on my all the mods 7 server encountered crashes once they had placed the book of shadows. I'm attaching the latest.log and crash report.

https://gist.github.com/Rover656/c51146e12db154797a063903106c7611
https://gist.github.com/Rover656/ab3a5700f16ef2bd5082f12e4c867672

**Comment by nomnomaproved** [comment]
having same problem when trying  to load in but my other friends can load in fine 

https://gist.github.com/nomnomaproved/48d25303d106ca81e395ffb6c9ae556d   ( crash report ) 
https://gist.github.com/nomnomaproved/4fe6ef809605e9e14a777fdff4d21476   ( latest logs )

**Comment by JoeFoxe** [comment]
Thanks both of you, I will look into this asap. I think there is something to do with not syncing properly. im not sure what would cause the desync but I think I just need to make something to ask for a resync if its not synced then it "should" work. but this may take some time so please bare with me

**Comment by winnetrie83** [comment]
I can confirm the same issue.

https://pastebin.com/jy9bGJ7u

**Comment by JoeFoxe** [comment]
fixed in the latest build 0.2.2, thanks for all the reports, got it all solved finally
