### ISSUE TITLE
BookEntry NullPointerException

### ISSUE THREAD

**Issue by XZot1K** [JoeFoxe/Hexerei-1.18#47]
Upon clicking the floating book above a table, it immediately crashed the client on the latest 0.2.1 build release 7/27/2022.

`Cannot read field "chapterList" because "bookEntries" is null`

As stated in the error, it looks like the crash is caused by obtaining chapters though the "bookEntries" object return null due to the book being empty. 

**Attached Crash Report**
[crash-2022-07-29_02.23.17-client.txt](https://github.com/JoeFoxe/Hexerei-1.18/files/9216825/crash-2022-07-29_02.23.17-client.txt)

**Comment by winnetrie83** [comment]
I can confirm the same issue. 

https://pastebin.com/jy9bGJ7u

**Comment by JoeFoxe** [comment]
fixed in the latest 0.2.2 version
