### ISSUE TITLE
Coffer will delete its contents when taken.

### ISSUE THREAD

**Issue by Thunder-Nova** [JoeFoxe/Hexerei-1.18#5]
So I found a Dark Coven, and started looting, found a naturally spawned Coffer.

Puts items in there hoping it will act as a shulker box (love how the items shows up when placed), then breaks it, placed it back but it was empty.

Played on All the mods 7 version 0.2.11, which has Hexerei v0.1.9

**Comment by JoeFoxe** [comment]
I do apologize for the bug D: I do have it fixed for the next patch incoming so no worries :) I spotted this bug a few days ago. somehow code got changed so it was no longer saving it properly. but now it  should be (well soon once I post the update, with a whole new broom system

**Comment by Thunder-Nova** [comment]
No prob. I do really like the Coffer design, though, the instant break is a bit concerning.

If I could make a suggestion:
If it is possible that the 1st punch closes the case, and the 2nd lets the player pick it up. The reason behind this, is that the Coffer can be very much use as a nice decoration as well. And don't want to accidently break it when punching a mob in the way and such.

Or sneak punch to grab the coffer.

**Comment by JoeFoxe** [comment]
Yea that is a pretty good suggestion! I might look into how the sneak punching will go, seems like it could be a good resolution for that. just have to see if its not too annoying to always do that but I think it should be fine. also the update is now out :)
