### ISSUE TITLE
[1.19.2] Automated Harvesting

### ISSUE THREAD

**Issue by HalcyonSeas73** [JoeFoxe/Hexerei-1.18#53]
Minecraft version: 1.19.2
Forge version: 43.1.1
Hexerei version: 0.2.4

When trying to automate harvesting- such as with Cyclic's Harvester- Hexerei's crops drop as their bush rather than their drops. Expected behaviour is that they would be harvested like Sweet Berries would.
![Untitled](https://user-images.githubusercontent.com/84727791/187011175-01b0b275-7b71-492e-8299-f3debbae0f30.png)
![Untitled2](https://user-images.githubusercontent.com/84727791/187011208-24643450-0625-47ca-9c94-9d90c18091bb.png)

**Comment by SargeRyong** [comment]
To add to this, Create harvesters appear to harvest the plants correctly (it returns to its lowest growth stage), but receive no items from the plants at all.

**Comment by HalcyonSeas73** [comment]
Moved [issue ](https://github.com/JoeFoxe/Hexerei-1.19/issues/17)over to Hexerei's 1.19 repo
