### ISSUE TITLE
The Broom Descend key is the same as the dismount key

### ISSUE THREAD

**Issue by aaronhowser1** [JoeFoxe/Hexerei-1.18#60]
![image](https://user-images.githubusercontent.com/15698722/189481842-2a25ecf4-93f9-4af9-a0ae-0e592be2dcf6.png)

Pressing this just makes you dismount and fall to the ground

**Comment by JoeFoxe** [comment]
yea so I suppose you can change that key as its a keybind :P

**Comment by aaronhowser1** [comment]
Still, the default key could be something else

**Comment by JoeFoxe** [comment]
or mojang could do a normal crouch button which is control and not shift 🙃

**Comment by aaronhowser1** [comment]
One of these options is much more possible to happen though

**Comment by JoeFoxe** [comment]
the most possible is you changing it yourself :)

**Comment by Officialy** [comment]
Wouldn't this be considered a bug? 

If I was to install just your mod, and change nothing about it. You'd still fall to the ground?

In this case, you're wanting everyone who uses your mod to either re-bind vanilla keys, or to re-bind your mods descend key...

**Comment by wizen** [comment]
Add another voice to the side of changing default key bindings. Your default config causes players to get kicked from the server if flying is disabled. Fix your mod please.
