### ISSUE TITLE
[1.16.5] [0.1.4] Singleplayer "server" crashes

### ISSUE THREAD

**Issue by qdoyonnas** [JoeFoxe/Hexerei-1.18#61]
Hi, I am having an odd issue that unfortunately I do not have a huge amount of information for. I have about 90 mods installed, but this issue only occurs when Hexerei is active.

When I move to a specific location in my world the local server "crashes" and everything in game stops working. I can continue to move around and break blocks. But nothing drops from broken blocks, mobs do not spawn or move, chests/levers cannot be interacted with.

Unfortunately, nothing appears in the logs of the game. The only note is something like "Can't keep up! Is the server overloaded? Running 2004ms or 40 ticks behind". But no matter how long the game continues, or where the player moves, the server never recovers.

The only valuable piece of information I have is that the crash happens near a Cyclops Cave from Ice and Fire mod. I suspect the issue might be something from Hexerei spawning as loot in one of the chests.

Sorry I can't provide more information.

**Comment by JoeFoxe** [comment]
thats no worries, I cant really help 1.16.5 is discontinued and I havent come across this in the later versions so seems to be fine
