### ISSUE TITLE
[Feature Request] Config option to disable willow tree generation 1.18.2

### ISSUE THREAD

**Issue by Sember225** [JoeFoxe/Hexerei-1.18#67]
Can there be an option to disable these? I'm running into multiple kinds of willow trees in my world. Just wondering.

**Comment by FreshAlacrity** [comment]
Willow wood is important for making things in Hexerei so you'd also need to alter some recipes as well, and it also appears in parts of the Dark Coven villages too so I'd recommend using Block Swap or similar instead. ^^

**Comment by Sember225** [comment]
Thank you, I know asking for stuff you worked hard on to be optional is a bit rude. Appreciate the good will!
