### ISSUE TITLE
[1.19.2] class net.minecraft.world.level.block.entity.CampfireBlockEntity cannot be cast to class net.joefoxe.hexerei.tileentity.CandleTile

### ISSUE THREAD

**Issue by theArhar** [JoeFoxe/Hexerei-1.18#68]
[crash-2022-11-02_16.41.56-server.txt](https://github.com/JoeFoxe/Hexerei-1.18/files/9920919/crash-2022-11-02_16.41.56-server.txt)

**Comment by Saereth** [comment]
Also getting this https://gist.github.com/Saereth/19bb15b107483a8d2c875a7939970e9a

**Comment by Darkfiend009** [comment]
Same here: https://pastebin.com/XW9usZCs

**Comment by Gbergz** [comment]
Confirm. Still an issue.

**Comment by Konclan** [comment]
Currently having this issue in AllTheMods 8 in a desert structure. Seems like the puzzles are trying to light a campfire and its just crashing the server.

**Comment by JoeFoxe** [comment]
This is fixed in the latest update, please be sure to update hexerei to the latest. And let the ATM team know to update as well
