### ISSUE TITLE
Blood levels in mixing cauldron don't update when jumping on the blood sigil

### ISSUE THREAD

**Issue by alexblaauw** [JoeFoxe/Hexerei-1.18#8]
I was experimenting with the mixing cauldron and noticed the blood level doesn't rise beyond the first time. Continuing to jump on the blood sigil at the bottom does add blood, but doesn't update the visual. However, when updating the cauldron by retrieving blood using a bucket/bottle and the level jumped up to what it was supposed to be. I was playing version 0.1.12 of hexerei and forge version 39.0.17.

**Comment by JoeFoxe** [comment]
Fixed in the next update :) im pretty sure
