### ISSUE TITLE
Mixing Cauldron UI error and missing Mixing Cauldron Recipes JEI

### ISSUE THREAD

**Issue by itsdeadfrosty** [JoeFoxe/Hexerei-1.18#93]
![2023-05-13_09 12 44](https://github.com/JoeFoxe/Hexerei-1.18/assets/132015237/8094bafb-06fd-448c-b0fd-9407ce688946)
![2023-05-13_09 13 34](https://github.com/JoeFoxe/Hexerei-1.18/assets/132015237/d9605767-f702-4e68-b42c-9a83a1fd4dd5)

**Comment by itsdeadfrosty** [comment]
RIP dead mod

**Comment by LykiaOokami** [comment]
Still an issue - 1.18.2 and JEI shows no recipe
