### ISSUE TITLE
Hazel/Mahogany/Willow Drying Rack Item Duplication Bug/Glitch [1.19.2/Hexerei 0.3.0]

### ISSUE THREAD

**Issue by Pelkel** [JoeFoxe/Hexerei-1.18#94]
The three crafted drying racks of Witch Hazel, Mahogany, and Willow are all bugged or glitched in such a way that they cause item duplication.

In order to test/recreate:
Step 1. Take any of those three types of drying racks and place them in the world.  
Step 2. Then take any item that can be placed on said rack, such as a diamond, book, etc. and place it on the rack like normal.  
Step 3. Break the drying rack with the item still on said rack.

You will then get a second copy of the item in question.

**Comment by Pelkel** [comment]
I don't know if video links are allowed, but I recorded and posted the bug in a private video to youtube to show what happens.[Found Here](https://youtu.be/omyvJTTgg-U)

**Comment by JoeFoxe** [comment]
you can update to the latest version 0.3.1 for the fix :)
